# Theme: omaled
# By: Brian Blakely

# Main bg
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#E66063"

# Title color for boxes
theme[title]="#EC8385"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#FF0022"

# Background color of selected item in processes box
theme[selected_bg]="#860111"

# Foreground color of selected item in processes box
theme[selected_fg]="#F6CACC"

# Color of inactive/disabled text
theme[inactive_fg]="#AC1C1E"

# Misc colors for processes box including mini cpu graphs,
# details memory graph and details status text
theme[proc_misc]="#E35053"

# Cpu box outline color
theme[cpu_box]="#DD2C2F"

# Memory/disks box outline color
theme[mem_box]="#BD1F21"

# Net up/down box outline color
theme[net_box]="#AC1C1E"

# Processes box outline color
theme[proc_box]="#D02224"

# Box divider line and small boxes line color
theme[div_line]="#9C191B"

# Temperature graph colors
theme[temp_start]="#BD1F21"
theme[temp_mid]="#E66063"
theme[temp_end]="#FF0022"

# CPU graph colors
theme[cpu_start]="#BD1F21"
theme[cpu_mid]="#E66063"
theme[cpu_end]="#FF0022"

# Mem/Disk free meter
theme[free_start]="#BD1F21"
theme[free_mid]="#E66063"
theme[free_end]="#FF0022"

# Mem/Disk cached meter
theme[cached_start]="#BD1F21"
theme[cached_mid]="#E66063"
theme[cached_end]="#FF0022"

# Mem/Disk available meter
theme[available_start]="#BD1F21"
theme[available_mid]="#E66063"
theme[available_end]="#FF0022"

# Mem/Disk used meter
theme[used_start]="#BD1F21"
theme[used_mid]="#E66063"
theme[used_end]="#FF0022"

# Download graph colors
theme[download_start]="#BD1F21"
theme[download_mid]="#E66063"
theme[download_end]="#FF0022"

# Upload graph colors
theme[upload_start]="#BD1F21"
theme[upload_mid]="#E66063"
theme[upload_end]="#FF0022"
