mode = "dark"

accent = "#5A000B"
# This refers to "selection background"
selection = "#860111"
# This refers to "muted text"
muted = "#5A000B"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#5A000B"

# For herdr, "foreground" should be legible on "muted"
# For yazi, "foreground" should be legible on "blue"
foreground = "#E66063"
dark_foreground = "#DD2C2F"
light_foreground = "#EC8385"
bright_foreground = "#F6CACC"

red = "#DD2C2F"
yellow = "#E66063"
orange = "#E35053"
green = "#BD1F21"
cyan = "#EC8385"
# For yazi, "blue" should be legible on "background"
blue = "#AC1C1E"
magenta = "#F1A7A9"
brown = "#9C191B"

bright_red = "#FF0022"
bright_yellow = "#F6CACC"
bright_green = "#E35053"
bright_cyan = "#F1A7A9"
bright_blue = "#D02224"
bright_magenta = "#F6CACC"
