mode = "dark"

accent = "#FF0022"
# This refers to "selection background"
selection = "#860111"
# This refers to "muted text"
muted = "#E35053"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#5A000B"

foreground = "#EC8385"
dark_foreground = "#E66063"
light_foreground = "#F1A7A9"
bright_foreground = "#F6CACC"

red = "#DD2C2F"
yellow = "#E66063"
orange = "#E35053"
green = "#D02224"
cyan = "#EC8385"
blue = "#E66063"
magenta = "#F1A7A9"
brown = "#BD1F21"

bright_red = "#FF0022"
bright_yellow = "#F6CACC"
bright_green = "#E66063"
bright_cyan = "#F1A7A9"
bright_blue = "#EC8385"
bright_magenta = "#F6CACC"
